#!/usr/bin/env python
import snmp_helper
community= 'galileo'
snmp_port1=7961
snmp_port2= 8061
IP = '50.76.53.27'
snmp1 = (IP, community, snmp_port1)
snmp2 = (IP, community, snmp_port2)
OID1='1.3.6.1.2.1.1.5.0'
OID2='1.3.6.1.2.1.1.1.0'
snmp_data=snmp_helper.snmp_get_oid(snmp1, oid=OID1)
output = snmp_helper.snmp_extract(snmp_data)
print "sysName of pynet-rtr1 \n"
print output
snmp_data=snmp_helper.snmp_get_oid(snmp1, oid=OID2)
output = snmp_helper.snmp_extract(snmp_data)
print "sysDescr of pynet-rtr1 \n"
print output
snmp_data=snmp_helper.snmp_get_oid(snmp2, oid=OID1)
output = snmp_helper.snmp_extract(snmp_data)
print "@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@\n"
print "sysName of pynet-rtr2 \n"
print output
snmp_data=snmp_helper.snmp_get_oid(snmp2, oid=OID2)
output = snmp_helper.snmp_extract(snmp_data)
print "sysDescr of pynet-rtr2 \n"
print output

