---
- hosts: local
  tasks:
    - name: configuration file
      template: src=/home/santiago/Pythoncourse/Ansible/access_switch.j2
                    dest=/home/santiago/Pythoncourse/Ansible/{{item.hostname}}.txt
      with_items:
        - {hostname: SW01, secret: cisco, access_vlan: 10, ip_addr: 192.168.10.1, default_gateway: 192.168.10.10, snmp_community: galileo, DHCPV3: False }
        - {hostname: SW02, secret: cisco, access_vlan: 10, ip_addr: 192.168.20.1, default_gateway: 192.168.20.10, snmp_community: galileo, DHCPV3: False }
        - {hostname: SW03, secret: cisco, access_vlan: 10, ip_addr: 192.168.30.1, default_gateway: 192.168.30.10, snmp_community: galileo, DHCPV3: False }
        - {hostname: SW04, secret: cisco, access_vlan: 10, ip_addr: 192.168.40.1, default_gateway: 192.168.40.10, snmp_community: galileo, DHCPV3: False }
        - {hostname: SW05, secret: cisco, access_vlan: 10, ip_addr: 192.168.50.1, default_gateway: 192.168.50.10, snmp_community: galileo, DHCPV3: True } 
